/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.13.2.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v12.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import ClientBase from "./base/ClientBase";

export class BluetoothClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super();
        this.http = http ? http : <any>window;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * @param ownHardwareAddress (optional) 
     * @param body (optional) 
     * @return Success
     */
    bluetooth(ownHardwareAddress?: string | undefined, body?: NearbyBluetooth[] | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Bluetooth?";
        if (ownHardwareAddress === null)
            throw new Error("The parameter 'ownHardwareAddress' cannot be null.");
        else if (ownHardwareAddress !== undefined)
            url_ += "ownHardwareAddress=" + encodeURIComponent("" + ownHardwareAddress) + "&";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_ = <RequestInit>{
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processBluetooth(_response);
        });
    }

    protected processBluetooth(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(<any>null);
    }

    /**
     * @param hardwareAddress (optional) 
     * @return Success
     */
    studentProximities(hardwareAddress?: string | undefined): Promise<NearbyBluetooth[]> {
        let url_ = this.baseUrl + "/api/Bluetooth/StudentProximities?";
        if (hardwareAddress === null)
            throw new Error("The parameter 'hardwareAddress' cannot be null.");
        else if (hardwareAddress !== undefined)
            url_ += "hardwareAddress=" + encodeURIComponent("" + hardwareAddress) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStudentProximities(_response);
        });
    }

    protected processStudentProximities(response: Response): Promise<NearbyBluetooth[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <NearbyBluetooth[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<NearbyBluetooth[]>(<any>null);
    }

    /**
     * @return Success
     */
    allProximities(): Promise<{ [key: string]: NearbyBluetooth[]; }> {
        let url_ = this.baseUrl + "/api/Bluetooth/AllProximities";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAllProximities(_response);
        });
    }

    protected processAllProximities(response: Response): Promise<{ [key: string]: NearbyBluetooth[]; }> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <{ [key: string]: NearbyBluetooth[]; }>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<{ [key: string]: NearbyBluetooth[]; }>(<any>null);
    }
}

export class ClassroomClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super();
        this.http = http ? http : <any>window;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * @return Success
     */
    classroom(): Promise<string[]> {
        let url_ = this.baseUrl + "/api/Classroom";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processClassroom(_response);
        });
    }

    protected processClassroom(response: Response): Promise<string[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <string[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<string[]>(<any>null);
    }
}

export class DebugClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super();
        this.http = http ? http : <any>window;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * @param studentId (optional) 
     * @param event (optional) 
     * @return Success
     */
    addEvent(studentId?: string | undefined, event?: UrgentEvent | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Debug/AddEvent?";
        if (studentId === null)
            throw new Error("The parameter 'studentId' cannot be null.");
        else if (studentId !== undefined)
            url_ += "studentId=" + encodeURIComponent("" + studentId) + "&";
        if (event === null)
            throw new Error("The parameter 'event' cannot be null.");
        else if (event !== undefined)
            url_ += "event=" + encodeURIComponent("" + event) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "PUT",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processAddEvent(_response);
        });
    }

    protected processAddEvent(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(<any>null);
    }

    /**
     * @param studentId (optional) 
     * @param event (optional) 
     * @return Success
     */
    setVocalActivity(studentId?: string | undefined, event?: UrgentEvent | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Debug/SetVocalActivity?";
        if (studentId === null)
            throw new Error("The parameter 'studentId' cannot be null.");
        else if (studentId !== undefined)
            url_ += "studentId=" + encodeURIComponent("" + studentId) + "&";
        if (event === null)
            throw new Error("The parameter 'event' cannot be null.");
        else if (event !== undefined)
            url_ += "event=" + encodeURIComponent("" + event) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "PUT",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSetVocalActivity(_response);
        });
    }

    protected processSetVocalActivity(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(<any>null);
    }

    /**
     * @param studentId (optional) 
     * @param event (optional) 
     * @return Success
     */
    setActivity(studentId?: string | undefined, event?: UrgentEvent | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Debug/SetActivity?";
        if (studentId === null)
            throw new Error("The parameter 'studentId' cannot be null.");
        else if (studentId !== undefined)
            url_ += "studentId=" + encodeURIComponent("" + studentId) + "&";
        if (event === null)
            throw new Error("The parameter 'event' cannot be null.");
        else if (event !== undefined)
            url_ += "event=" + encodeURIComponent("" + event) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "PUT",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSetActivity(_response);
        });
    }

    protected processSetActivity(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(<any>null);
    }
}

export class StudentsClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super();
        this.http = http ? http : <any>window;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * @return Success
     */
    students(): Promise<Student[]> {
        let url_ = this.baseUrl + "/api/Students";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processStudents(_response);
        });
    }

    protected processStudents(response: Response): Promise<Student[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Student[]>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Student[]>(<any>null);
    }

    /**
     * @param ownHardwareAddress (optional) 
     * @param activity (optional) 
     * @return Success
     */
    updateActivity(ownHardwareAddress?: string | undefined, activity?: Activity | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Students/UpdateActivity?";
        if (ownHardwareAddress === null)
            throw new Error("The parameter 'ownHardwareAddress' cannot be null.");
        else if (ownHardwareAddress !== undefined)
            url_ += "ownHardwareAddress=" + encodeURIComponent("" + ownHardwareAddress) + "&";
        if (activity === null)
            throw new Error("The parameter 'activity' cannot be null.");
        else if (activity !== undefined)
            url_ += "activity=" + encodeURIComponent("" + activity) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "PUT",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateActivity(_response);
        });
    }

    protected processUpdateActivity(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(<any>null);
    }

    /**
     * @param ownHardwareAddress (optional) 
     * @param activity (optional) 
     * @return Success
     */
    updateVocalActivity(ownHardwareAddress?: string | undefined, activity?: VocalActivity | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Students/UpdateVocalActivity?";
        if (ownHardwareAddress === null)
            throw new Error("The parameter 'ownHardwareAddress' cannot be null.");
        else if (ownHardwareAddress !== undefined)
            url_ += "ownHardwareAddress=" + encodeURIComponent("" + ownHardwareAddress) + "&";
        if (activity === null)
            throw new Error("The parameter 'activity' cannot be null.");
        else if (activity !== undefined)
            url_ += "activity=" + encodeURIComponent("" + activity) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "PUT",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateVocalActivity(_response);
        });
    }

    protected processUpdateVocalActivity(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(<any>null);
    }

    /**
     * @param ownHardwareAddress (optional) 
     * @return Success
     */
    activity(ownHardwareAddress?: string | undefined): Promise<Activity> {
        let url_ = this.baseUrl + "/api/Students/Activity?";
        if (ownHardwareAddress === null)
            throw new Error("The parameter 'ownHardwareAddress' cannot be null.");
        else if (ownHardwareAddress !== undefined)
            url_ += "ownHardwareAddress=" + encodeURIComponent("" + ownHardwareAddress) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processActivity(_response);
        });
    }

    protected processActivity(response: Response): Promise<Activity> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <Activity>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Activity>(<any>null);
    }

    /**
     * @param ownHardwareAddress (optional) 
     * @return Success
     */
    vocalActivity(ownHardwareAddress?: string | undefined): Promise<VocalActivity> {
        let url_ = this.baseUrl + "/api/Students/VocalActivity?";
        if (ownHardwareAddress === null)
            throw new Error("The parameter 'ownHardwareAddress' cannot be null.");
        else if (ownHardwareAddress !== undefined)
            url_ += "ownHardwareAddress=" + encodeURIComponent("" + ownHardwareAddress) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_ = <RequestInit>{
            method: "GET",
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processVocalActivity(_response);
        });
    }

    protected processVocalActivity(response: Response): Promise<VocalActivity> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : <VocalActivity>JSON.parse(_responseText, this.jsonParseReviver);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<VocalActivity>(<any>null);
    }
}

export enum Activity {
    Sitting = "Sitting",
    Walking = "Walking",
    Running = "Running",
    Playing = "Playing",
    Fighting = "Fighting",
    Falling = "Falling",
}

export interface EventHistory {
    student?: Student;
    event?: UrgentEvent;
    date?: Date;
}

export interface NearbyBluetooth {
    hardwareAddress?: string | undefined;
    rssi?: number;
}

export interface Student {
    id?: string;
    deviceHardwareAddress?: string | undefined;
    name: string;
    age: number;
    teachers?: Teacher[] | undefined;
}

export interface Teacher {
    id?: string;
    firstName?: string | undefined;
    lastName?: string | undefined;
    students?: Student[] | undefined;
}

export enum UrgentEvent {
    Falling = "Falling",
    Crying = "Crying",
    PeePeePooPoo = "PeePeePooPoo",
    Dying = "Dying",
}

export enum VocalActivity {
    Talking = "Talking",
    Shouting = "Shouting",
    Crying = "Crying",
    Silent = "Silent",
    Laughing = "Laughing",
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}